### PR TITLE
added vault_command resource

### PR DESCRIPTION
**Pull request by atheiman**
I added a vault_command resource to be used to test configuration within a running vault server (system config, mounted secrets engines, enabled auth methods, enabled audit devices, etc) via the `vault` cli.

```ruby
control 'vault_resources' do
  # VAULT_ADDR and VAULT_TOKEN env vars should first be exported
  describe vault_command('status') do
    its('stdout') { should match(/^Sealed\s+false\s*$/) }
    its('stdout') { should match(/^Version\s+0\.11\.\d+\s*$/) }
    its('stdout') { should match(/^Cluster Name\s+vault-cluster-\w+\s*$/) }
    # json is the stdout parsed as JSON. if stdout could not be parsed as JSON, json is nil
    its('json') { should be_nil }
    its('stderr') { should cmp '' }
  end
   # If the output can be parsed as JSON, the top level keys of the JSON response are available
  describe vault_command('status -format=json') do
    its('sealed') { should cmp false }
    its('version') { should match(/0\.11\.\d+/) }
    its('cluster_name') { should match(/vault-cluster-\w+/) }
    its('stderr') { should cmp '' }
  end
   # If VAULT_ADDR and VAULT_TOKEN env vars are not set, they can be specified in vault_command()
  describe vault_command('secrets list -format=json', vault_addr: 'http://localhost:8200', vault_token: 'root-token') do
    its('secret/') { should include('type' => 'kv', 'options' => { 'version' => '2' }) }
    # json is the stdout parsed as JSON. if stdout could not be parsed as JSON, json is nil
    its('json') { should_not include('bad-secret-path/')}
    its('stderr') { should cmp '' }
  end
end
```

- [x] code
- [x] tests
- [x] tests for vault_command running in travis
- [x] documentation in readme

### CODE REVIEW

**Comment by atheiman** [comment]
@martezr let me know if there is anything else you'd like to see in this. I was gonna do this in my own inspec project, but I noticed that you already had an `inspec-vault`project so I thought this would be a good spot for it

**Comment by martezr** [comment]
@atheiman Give me a day or two to review the code and functionality added. The one initial thought I had was around whether it makes sense to use the vault binary or the vault API to provide a cleaner method for performing the checks. InSpec 3.0 also released the capability to create plugins for integrating InSpec with API endpoints.

**Comment by atheiman** [comment]
i think leaving the vault binary usage in `vault_command()` and also adding vault api tests with `vault_api()` can be done separately. I think more people are familiar with Vault CLI than directly with vault http api calls, so vault_command will probably be more user-friendly.

I think for how little code this took its extremely useful.. Im currently using the `vault_command()` resource to test a vault terraform repo

**Comment by atheiman** [comment]
did you get a chance to look at this @martezr ?

it looks like a big change at first, but really its all docs and tests other than `libraries/vault_command.rb` and I based that file on [the inspec example library `gordon_config.rb`](https://github.com/inspec/inspec/blob/master/examples/profile/libraries/gordon_config.rb)

**Pull request merged**
